name: Triggered from GitLab

on:
  repository_dispatch:
    types: [gitlab-trigger]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run something
        run: echo "Triggered from GitLab"